name: kadinatlasi
description: "Kadın Atlası - Women's health and wellness mobile app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4

  # Navigation
  go_router: ^13.2.0

  # Network & API
  dio: ^5.4.0
  json_annotation: ^4.8.1
  connectivity_plus: ^4.0.2

  # Local Storage
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  path: ^1.8.3
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # UI & Styling
  flutter_html: ^3.0.0-beta.2
  cached_network_image: ^3.3.1

  # Utilities
  intl: ^0.20.2
  uuid: ^4.3.3
  equatable: ^2.0.5

  # Development
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.11
  json_serializable: ^6.7.1
  drift_dev: ^2.14.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env.local
    - assets/images/
    - assets/icons/

  # fonts:
  # - family: Inter
  #   fonts:
  #     - asset: assets/fonts/Inter-Regular.ttf
  #     - asset: assets/fonts/Inter-Medium.ttf
  #       weight: 500
  #     - asset: assets/fonts/Inter-SemiBold.ttf
  #       weight: 600
  #     - asset: assets/fonts/Inter-Bold.ttf
  #       weight: 700
